// <auto-generated />
namespace UFCQuixada.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterationTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterationTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201510201645301_AlterationTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
